export * from "./register/button-register";
export * from "./loading";
export * from "./register/terms-check-box";
export * from "./register/input-phone-number";
export * from "./register/footer-link";
export * from './otp/otp-header';
export * from './otp/otp-input';
export * from './otp/otp-info-box';
export * from './otp/otp-action-button';
export * from './register/verification-modal'
