import { StyleSheet } from "react-native";

export const ContactStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#FFFFFF",
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		padding: 10,
		backgroundColor: "#F5F5F5",
		borderBottomWidth: 1,
		borderBottomColor: "#DDD",
	},
	headerTitle: {
		color: "#000",
		fontSize: 18,
		fontWeight: "bold",
		flex: 1,
		textAlign: "center",
	},
	headerSubTitle: {
		color: "#555",
		fontSize: 14,
	},
	searchContainer: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 10,
		paddingVertical: 5,
		backgroundColor: "#F5F5F5",
		borderBottomWidth: 1,
		borderBottomColor: "#DDD",
	},
	searchIconLeft: {
		marginRight: 10,
	},
	searchIconRight: {
		marginLeft: 10,
	},
	searchInput: {
		flex: 1,
		color: "#000",
		fontSize: 16,
		paddingVertical: 5,
	},
	headerButtons: {
		flexDirection: "row",
		justifyContent: "space-around",
		backgroundColor: "#F5F5F5",
	},
	headerButtonText: {
		color: "#555",
		fontSize: 16,
	},
	tabActive: {
		color: "#007AFF",
		fontWeight: "bold",
	},
	menuContainer: {
		padding: 10,
	},
	menuItem: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		backgroundColor: "#F5F5F5",
		borderRadius: 5,
		marginBottom: 10,
	},
	menuIcon: {
		backgroundColor: "#007AFF",
		borderRadius: 5,
		padding: 7,
		marginRight: 10,
		marginLeft: 10,
	},
	menuText: {
		color: "#000",
		fontSize: 16,
	},
	contactItem: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		paddingHorizontal: 15,
		borderBottomWidth: 1,
		borderBottomColor: "#DDD",
	},
	avatar: {
		width: 50,
		height: 50,
		borderRadius: 25,
		marginRight: 10,
	},
	actionContainer: {
		flexDirection: "row",
	},
	userName: {
		fontSize: 16,
		fontWeight: "bold",
	},
	contactName: {
		color: "#000",
		fontSize: 16,
		fontWeight: "bold",
		marginBottom: 5,
	},
	tabSwitchContainer: {
		flexDirection: "row",
		justifyContent: "space-around",
		paddingVertical: 10,
		backgroundColor: "#F5F5F5",
		borderBottomWidth: 2,
		borderBottomColor: "#DDD",
	},
	tabText: {
		color: "#555",
		fontSize: 16,
	},
	groupHeader: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		paddingHorizontal: 15,
		backgroundColor: "#F5F5F5",
		borderBottomWidth: 1,
		borderBottomColor: "#DDD",
	},
	groupHeaderText: {
		color: "#000",
		fontSize: 16,
	},
	noDataText: {
		color: "#555",
		fontSize: 16,
		textAlign: "center",
		marginTop: 20,
	},
	searchResultContainer: {
		flexDirection: "row",
		alignItems: "center",
		padding: 10,
		borderBottomWidth: 1,
		borderBottomColor: "#ddd",
	},
	addFriendButton: {
		backgroundColor: "#007AFF",
		paddingVertical: 5,
		paddingHorizontal: 10,
		borderRadius: 5,
	},
	cancelRequestButton: {
		backgroundColor: "#FF3B30",
		paddingVertical: 5,
		paddingHorizontal: 10,
		borderRadius: 5,
	},
	actionButtonText: {
		color: "#FFF",
		fontSize: 14,
		fontWeight: "bold",
	},
	actionText: {
		color: "#fff",
		fontWeight: "bold",
	},
	sectionTitle: {
		color: "#000",
		fontSize: 18,
		fontWeight: "bold",
		paddingHorizontal: 15,
		paddingVertical: 10,
	},
	birthdayItem: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		paddingHorizontal: 15,
		borderBottomWidth: 1,
		borderBottomColor: "#DDD",
	},
	birthdayText: {
		color: "#555",
		fontSize: 14,
	},
	chatButton: {
		padding: 5,
	},
	groupNameContainer: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 15,
		paddingVertical: 10,
		backgroundColor: "#F5F5F5",
		borderBottomWidth: 1,
		borderBottomColor: "#DDD",
	},
	groupNameInput: {
		flex: 1,
		color: "#000",
		fontSize: 16,
		marginLeft: 10,
	},
	friendItem: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		paddingHorizontal: 15,
		borderBottomWidth: 1,
		borderBottomColor: "#DDD",
	},
	checkbox: {
		width: 20,
		height: 20,
		borderWidth: 1,
		borderColor: "#000",
		borderRadius: 4,
		justifyContent: "center",
		alignItems: "center",
		marginRight: 10,
	},
	selectedFriendsContainer: {
		padding: 10,
		backgroundColor: "#F5F5F5",
		borderTopWidth: 1,
		borderTopColor: "#DDD",
	},
	selectedFriendItem: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 5,
		marginBottom: 5,
	},
	selectedAvatar: {
		width: 30,
		height: 30,
		borderRadius: 15,
		marginRight: 10,
	},
	selectedName: {
		color: "#000",
		fontSize: 14,
		flex: 1,
	},
	createGroupButton: {
		backgroundColor: "#007AFF",
		padding: 10,
		borderRadius: 5,
		alignItems: "center",
		marginTop: 10,
	},
	createGroupText: {
		color: "#FFF",
		fontSize: 16,
		fontWeight: "bold",
	},
	userRow: {
		flexDirection: "row",
		alignItems: "center",
		flex: 1,
	},
	requestDateText: {
		fontSize: 12,
		color: "#888",
		marginTop: 2,
	},
	contactContent: {
		flex: 1,
	},
	actionButtons: {
		flexDirection: "row",
		marginTop: 5,
	},
	noDataText: {
		color: "#666",
		fontSize: 16,
		textAlign: "center",
		marginTop: 20,
	},
	ButtonText: {
		color: "#FFF",
		fontSize: 14,
		fontWeight: "bold",
	},
	rejectButton: {
		marginRight: 10,
		backgroundColor: "#FF3B30",
		borderRadius: 5,
		paddingVertical: 8,
		paddingHorizontal: 12,
	},
	acceptButton: {
		backgroundColor: "#34C759",
		borderRadius: 5,
		paddingVertical: 8,
		paddingHorizontal: 12,
	},
	tabSwitchContainer: {
		flexDirection: "row",
		justifyContent: "space-around",
		paddingVertical: 10,
		borderBottomWidth: 1,
		borderBottomColor: "#ccc",
	},
	tabText: {
		fontSize: 16,
		color: "#666",
	},
	tabActive: {
		color: "#007AFF",
		fontWeight: "bold",
	},
});
